id: blackrock_international
fund_name_patterns:
  - "BlackRock\\s*International\\s*Fund"
schedule_header: "Schedule of Investments"
layout:
  type: two_column_line_numeric
  columns: 2
  shares_token_index: 0
  value_token_index: 1
instrument_headers:
  CommonStocks: "Common Stock"
stop_line_prefixes:
  - "Total Long-Term Investments"
  - "Total Long- Term Investments"
  - "Short-Term Securities"
  - "Affiliates"
  - "Fair Value Hierarchy"
stop_line_contains: []
noise_prefixes:
  - "(Cost:$"
  - "( Cost:$"
  - "Other Assets"
  - "Net Assets"
  - "Shares,"
  - "Affiliated Issuer"
  - "Institutional Shares"
  - "Level"
  - "BNM"
  - "â€¢ Level"


